language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
install:
  - mvn clean install -DskipTests=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
cache:
  directories:
  - $HOME/.m2
sudo: false
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
